export const Books = [
    {
        "id": 1,
        "title_book": "It ends with us",
        "writer_book" : "Colleen hover",
        "genre" : "Romance",
    },
    {
        "id": 2,
        "title_book": "It starts with us",
        "writer_book" : "Colleen hover",
        "genre" : "Romance",
    },
    {
        "id": 3,
        "title_book": "Onder de Italiaanse zon",
        "writer_book" : "Santa Montefiore",
        "genre" : "Romance",
    },
    {
        "id": 4,
        "title_book": "Onder de Ombuboom",
        "writer_book" : "Santa Montefiore",
        "genre" : "Romance",
    },
    {
        "id": 5,
        "title_book": "Het appartement aan central park",
        "writer_book" : "Fiona Davis",
        "genre" : "Romance",
    },
    {
        "id": 6,
        "title_book": "After we collided",
        "writer_book" : "Anna Todd",
        "genre" : "Romance",
    },
    {
        "id": 7,
        "title_book": "De chocolade Villa",
        "writer_book" : "Maria Nikolai",
        "genre" : "Romance",
    },
    {
        "id": 8,
        "title_book": "De zeven zussen (De zeven zussen #1)",
        "writer_book" : "Lucinda Riley",
        "genre" : "Romance",
    },
    {
        "id": 9,
        "title_book": "Storm (De zeven zussen #2)",
        "writer_book" : "Lucinda Riley",
        "genre" : "Romance",
    },
    {
        "id": 10,
        "title_book": "Het vlindereiland",
        "writer_book" : "Corina Boman",
        "genre" : "",
    },
    {
        "id": 11,
        "title_book": "A goods girl's guide to murder (a goods girl's guide to murder #1)",
        "writer_book" : "Holly jasckson",
        "genre" : "Romance",
    },
    {
        "id": 12,
        "title_book": "Bij het licht van de maan (De tuinen van devon #1)",
        "writer_book" : "Sante Montefiore",
        "genre" : "Romance",
    },
    {
        "id": 13,
        "title_book": "Het italiaanse Meisje",
        "writer_book" : "Lucinda Riley",
        "genre" : "Romance",
    },
    {
        "id": 14,
        "title_book": "De olijfboom",
        "writer_book" : "Lucinda Riley",
        "genre" : "Romance",
    },
    {
        "id": 15,
        "title_book": "Friends, Lovers, and the Big Terrible Thing",
        "writer_book" : "Matthew Perry",
        "genre" : "Romance",
    },
    {
        "id": 16,
        "title_book": "Het eiland",
        "writer_book" : "Victoria Hislop",
        "genre" : "Romance",
    },
    {
        "id": 17,
        "title_book": "Een avond in augustus",
        "writer_book" : "Victoria Hislop",
        "genre" : "Romance",
    },
    {
        "id": 18,
        "title_book": "het koninklijk huis",
        "writer_book" : "Herman Koch",
        "genre" : "Romance",
    },
    {
        "id": 19,
        "title_book": "Schaduw (De zeven zussen #3)",
        "writer_book" : "Lucinda Riley",
        "genre" : "Romance",
    },
    {
        "id": 20,
        "title_book": "Hoog Sensitieve personen: heo blijf je overeind als de wereld je overweldigt",
        "writer_book" : "Elaine N. Aron",
        "genre" : "Romance",
    },
    {
        "id": 21,
        "title_book": "Twisted Love (Twisted #1)",
        "writer_book" : "Ana Huang",
        "genre" : "Romance",
    },
    {
        "id": 22,
        "title_book": "Twisted Lies (Twisted #4)",
        "writer_book" : "Anan Huang",
        "genre" : "Romance",
    },
    {
        "id": 23,
        "title_book": "Twisted Games (Twisted #2)",
        "writer_book" : "Ana Huang",
        "genre" : "Romance",
    },
    {
        "id": 24,
        "title_book": "Shoe dog: A Memior by the Creator of nike",
        "writer_book" : "Phil Knight",
        "genre" : "Romance",
    },
    {
        "id": 25,
        "title_book": "Een tijdloze Liefde",
        "writer_book" : "Santa Montefiore",
        "genre" : "Romance",
    },
    {
        "id": 26,
        "title_book": "Sophia's Hoop (De kleuren van schoonheid #1)",
        "writer_book" : "Corina Bomann",
        "genre" : "Romance",
    },
    {
        "id": 27,
        "title_book": "Sophia's wens (de kleuren van schoonheid #2)",
        "writer_book" : "Corina Boman",
        "genre" : "Romance",
    },
    {
        "id": 28,
        "title_book": "Sophia's Triomf (de kleuren van schoonheid #3)",
        "writer_book" : "Corina Boman",
        "genre" : "Romance",
    },

    {
        "id": 29,
        "title_book": "Twisted Hate (Twisted #3)",
        "writer_book" : "Ana Huang",
        "genre" : "Romance",
    },
    

]